## NumPy概述
NumPy是Python中科学计算的基础包。
它是一个Python库，提供多维数组对象，各种派生对象（如掩码数组和矩阵），以及用于数组快速操作的各种API，有包括数学、逻辑、形状操作、排序、选择、输入输出、离散傅立叶变换、基本线性代数，基本统计运算和随机模拟等等。

## 核心数据结构
NumPy的主要对象是同构多维数组ndarray

In [3]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape

(3, 5)

In [5]:
a.ndim

2

In [6]:
a.dtype.name

'int32'

In [7]:
a.itemsize

4

In [8]:
a.size

15

In [9]:
type(a)

numpy.ndarray

## 数组创建

In [11]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [12]:
a.dtype

dtype('int32')

In [13]:
b = np.array([1.2, 3.5, 5.1])
b

array([1.2, 3.5, 5.1])

In [14]:
b.dtype

dtype('float64')

In [15]:
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

## 基本操作

In [17]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
a,b

(array([20, 30, 40, 50]), array([0, 1, 2, 3]))

In [18]:
a-b

array([20, 29, 38, 47])

In [19]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [20]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

与许多矩阵语言不同，乘积运算符*在NumPy数组中按元素进行运算。矩阵乘积可以使用@运算符（在python> = 3.5中）或dot函数或方法执行

In [25]:
A = np.array( [[1,1],
...             [0,1]] )
B = np.array( [[2,0],
...             [3,4]] )
print(A)
print()
print(B)

[[1 1]
 [0 1]]

[[2 0]
 [3 4]]


In [26]:
A * B  

array([[2, 0],
       [0, 4]])

In [27]:
A @ B    

array([[5, 4],
       [3, 4]])

In [28]:
A.dot(B)  

array([[5, 4],
       [3, 4]])

## 一元操作

In [30]:
a = np.random.random((2,3))
a

array([[0.20007492, 0.57485531, 0.49925976],
       [0.44226649, 0.18851048, 0.54304821]])

In [31]:
a.sum(), a.min(),  a.max()

(2.4480151672411847, 0.18851048488307076, 0.5748553082607971)

In [32]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
 b.sum(axis=0),  b.sum(axis=1)      

(array([12, 15, 18, 21]), array([ 6, 22, 38]))

In [34]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

## 索引、切片和迭代

In [35]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [36]:
a[2]

8

In [37]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [38]:
a[ : :-1]    

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0], dtype=int32)

In [40]:
def f(x,y):
...     return 10*x+y

b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [41]:
b[2,3]

23

In [42]:
b[0:5, 1]  

array([ 1, 11, 21, 31, 41])

In [43]:
b[1:3, : ]    

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [45]:
# 当提供的索引少于轴的数量时，
# 缺失的索引被认为是完整的切片
b[-1]   

array([40, 41, 42, 43])

In [48]:
# 对多维数组进行 迭代（Iterating） 是
# 相对于第一个轴
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


## 形状操纵

In [50]:
a = np.floor(10*np.random.random((3,4)))
a.shape

(3, 4)

In [51]:
a.ravel()  # returns the array, flattened

array([1., 0., 2., 2., 4., 6., 0., 1., 4., 9., 8., 5.])

In [52]:
a.reshape(6,2)  # returns the array with a modified shape

array([[1., 0.],
       [2., 2.],
       [4., 6.],
       [0., 1.],
       [4., 9.],
       [8., 5.]])

In [53]:
a.T

array([[1., 4., 4.],
       [0., 6., 9.],
       [2., 0., 8.],
       [2., 1., 5.]])

## 不同数组堆叠

In [55]:
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))
print(a)
print(b)

[[7. 4.]
 [5. 2.]]
[[5. 3.]
 [1. 7.]]


In [56]:
np.vstack((a,b))

array([[7., 4.],
       [5., 2.],
       [5., 3.],
       [1., 7.]])

In [57]:
np.hstack((a,b))

array([[7., 4., 5., 3.],
       [5., 2., 1., 7.]])

## 数组拆分

In [58]:
a = np.floor(10*np.random.random((2,12)))
a

array([[9., 1., 4., 8., 3., 0., 9., 9., 9., 0., 1., 1.],
       [0., 3., 3., 7., 2., 1., 5., 7., 0., 0., 9., 7.]])

In [59]:
np.hsplit(a,3)

[array([[9., 1., 4., 8.],
        [0., 3., 3., 7.]]), array([[3., 0., 9., 9.],
        [2., 1., 5., 7.]]), array([[9., 0., 1., 1.],
        [0., 0., 9., 7.]])]

In [60]:
np.hsplit(a,(3,4))

[array([[9., 1., 4.],
        [0., 3., 3.]]), array([[8.],
        [7.]]), array([[3., 0., 9., 9., 9., 0., 1., 1.],
        [2., 1., 5., 7., 0., 0., 9., 7.]])]

## 拷贝和视图
当计算和操作数组时，有时会将数据复制到新数组中，有时则不会。

### 完全不复制

In [61]:
a = np.arange(12)
b = a

In [62]:
b is a

True

In [64]:
b.shape = 3,4
a.shape

(3, 4)

In [66]:
def f(x):
    print(id(x))
print(id(a))   
f(a)

1782216562448
1782216562448


### 视图或浅拷贝

In [67]:
c = a.view()
c is a

False

In [68]:
c.base is a  

True

In [69]:
c.shape = 2,6 
a.shape

(3, 4)

In [70]:
c[0,4] = 1234  
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [71]:
# 切片数组会返回一个视图
s = a[ : , 1:3]
s[:] = 10 
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

## 深拷贝
copy方法生成数组及其数据的完整副本

In [72]:
d = a.copy()   
d[0,0] = 9999
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

## 广播（Broadcasting）
- 广播允许算术运算期间处理具有不同形状的数组.
- 它可以在不制作不必要的数据副本的情况下实现这一点，通常导致高效的算法实现。
- 然而，有些情况下广播会导致内存使用效率低下，从而减慢计算速度。

In [74]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0   # b = np.array([2.0, 2.0, 2.0])
a * b

array([2., 4., 6.])

## 花式索引和索引技巧

In [76]:
# 使用索引数组进行索引
a = np.arange(12)**2 
i = np.array( [ 1,1,3,8,5 ] ) 
a[i]

array([ 1,  1,  9, 64, 25], dtype=int32)

In [77]:
j = np.array( [ [ 3, 4], [ 9, 7 ] ] ) 
a[j]

array([[ 9, 16],
       [81, 49]], dtype=int32)

In [78]:
# 使用布尔数组进行索引
a = np.arange(12).reshape(3,4)
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [79]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])